### ISSUE TITLE
Incorrectly handling return of Promise

### ISSUE THREAD

**Issue by bendebebe** [ortexx/express-brute-store-sequelize#4]
<code>[0] [1] (node:22196) Warning: a promise was created in a handler at node_modules\express-brute-store-sequelize\index.js:78:44 but was not returned from it, see http://goo.gl/rRqMUw
<\code>

Should be a pretty easy fix, just return inside of then instead of at the top level of the call.

**Comment by ortexx** [comment]
Done, thanks!
