### ISSUE TITLE
Sequelize v4 with operatorsAliases=false breaks clear.

### ISSUE THREAD

**Issue by brandonherzog** [ortexx/express-brute-store-sequelize#5]
The update to Sequelize v4 breaks the use of `$lt` in BruteStore.clear() if you configure operatorsAliases=false as in the tests.

If you don't specify the alias config you now get the following friendly warning from Sequelize:  
> String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators at node_modules\sequelize\lib\sequelize.js:242:13

**Comment by ortexx** [comment]
Done.
Thanks!
