### ISSUE TITLE
Promise return problem

### ISSUE THREAD

**Issue by cengizhan-ozcan** [ortexx/express-brute-store-sequelize#7]
i get error:

Warning: a promise was created in a handler at internal/timers.js:443:21 but was not returned from it, see http://goo.gl/rRqMUw

**Comment by ortexx** [comment]
I can't reproduce it. Please, send more information. What the version of the library and sequelize you use, what is your code.

**Comment by cengizhan-ozcan** [comment]
i am using version 2.0.0, node version node:11.13.0-alpine.
When i use express-brute with this library and send request to my route,
```
app.route('/service/user/login').post(
            this.bruteForce.loginBruteForce.getMiddleware({
                key: (req, res, next) => {
                    // prevent too many attempts for the same ip and email
                    return next(req.ip + "/" + req.body.email);
                },
            }),
            (req: any, res: Response, next: NextFunction) => {
             return  res.send('success.')
        });
```
code reach the return next(req.ip + "/" + req.body.email); line. After this point, i get the error.

**Comment by ortexx** [comment]
I tried the code close to yours and didn't get any error. You can create a simple repository or send me an archive with the code where i can reproduce it.

**Comment by cengizhan-ozcan** [comment]
I examined your code and i think some lines should be return. For instance:
`
reset(key, callback) {
    return this.model.destroy({ where: { key: key } }).then(() => {
      typeof callback == 'function' && callback();
     ------->> should be return;
    }).catch(function (err) {
      typeof callback == 'function' && callback(err);
      throw err;
    });
  };

return this.model.destroy(clause).then(() => {
      typeof callback == 'function' && callback();
    ----> Should be return;
    }).catch(function (err) {
      typeof callback == 'function' && callback(err);
      throw err;
    });
`

**Comment by ortexx** [comment]
I think you mix up something. You can always change the library code in your repository node_modules folder and check it out.

ps. `return;` in JS function is the same thing as not to return anything

**Comment by cengizhan-ozcan** [comment]
I found the problem. According to bluebird description at http://goo.gl/rRqMUw you need to return promise. If you don't have anything to return, you should return null.

In your code 
`get(key, callback) {
    return this.model.findOne({ where: { key: key } }).then((brute) => {
      if (!brute) {
        typeof callback == 'function' && callback();  
        return;     '--->> you should return null instead of just return;'
      }

      let data = brute.get();

      if (data.lifetime < new Date()) {
        return brute.destroy().then(() => {
          typeof callback == 'function' && callback();
          return;
        });
      }

      typeof callback == 'function' && callback(null, data);
      return data;
    })
    .catch(function (err) {
      typeof callback == 'function' && callback(err);
      throw err;
    });
  }
`
This change fixed my warning.

**Comment by ortexx** [comment]
Ok. I added this.
